### ISSUE TITLE
Clarify rules regarding coinbase genesis

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/slp-specifications#20]

**Comment by jcramer** [comment]
Coinbase transactions are fair game for creating a Genesis token transactions, there isn't anything in the SLP token type 1 (including NFT1 parent) rules preventing this.

As a consideration, validator implementations for NFT1 children should just be aware that a coinbase transaction with NFT1 child Genesis OP_RETURN can be immediately rejected as invalid since the coinbase input of `0000...0000` is a dead end.

I'm going to leave this open until I have a chance to investigate the NFT1 child genesis edge case for the different validators.

**Comment by jcramer** [comment]
Closing this since it seems like a non-issue, we can reopen if it's still an issue or point of confusion.
